# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By

from user import User


class TestLoginАndLogout:
    # before
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    # after
    def teardown_method(self, method):
        self.driver.quit()

    def test_login_and_logout(self):
        # Test name: Login and Logout
        user = User("san-100@bk.ru", "1234")
        # Step # | target | value | comment
        self.open_home_page()
        self.login(user.login, user.password)
        self.open_category()
        self.logout()

    def open_category(self):
        # click | css=.category-1:nth-child(1) > a |  |
        self.driver.find_element(By.CSS_SELECTOR, ".category-1:nth-child(1) > a").click()

    def logout(self):
        # click | linkText=Logout |  |
        self.driver.find_element(By.LINK_TEXT, "Logout").click()

    def login(self, login, password):
        # click | name=email |  |
        self.driver.find_element(By.NAME, "email").click()
        # type | name=email | san-100@bk.ru |
        self.driver.find_element(By.NAME, "email").send_keys(login)
        # click | name=password |  |
        self.driver.find_element(By.NAME, "password").click()
        # type | name=password | 1234 |
        self.driver.find_element(By.NAME, "password").send_keys(password)
        # click | name=login |  |
        self.driver.find_element(By.NAME, "login").click()

    def open_home_page(self):
        # open | /litecart/en/ |  |
        self.driver.get("http://localhost/litecart/en/")
